{{ if .Values.enableMonitoring }}
# For autodiscovery by Prometheus operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: metallb
    release: prometheus-operator
  name: metallb
  namespace: metallb-system
spec:
  endpoints:
  - port: metallb-metrics
  namespaceSelector:
    matchNames:
    - metallb-system
  selector:
    matchLabels:
      app: metallb
{{ end }}
