site_name: 'Lokomotive'
site_description: 'A minimal and free Kubernetes distribution' 
site_author: 'Kinvolk'
repo_name: 'kinvolk/lokomotive-kubernetes'
repo_url: 'https://github.com/kinvolk/lokomotive-kubernetes'
theme:
  name: 'material'
  feature:
    tabs: 'true'
  palette:
    primary: 'blue'
    accent: 'pink'
  logo: 'img/spin.png'
  favicon: 'img/favicon.ico'
  font:
    text: 'Roboto Slab'
    code: 'Roboto Mono'
extra_css:
  - 'stylesheets/lokomotive.css'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/kinvolk'
    - type: 'twitter'
      link: 'https://twitter.com/kinvolkio'
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - Home: 'index.md'
  - 'Announce': 'announce.md'
  - 'Architecture':
    - 'Concepts': 'architecture/concepts.md'
    - 'Operating Systems': 'architecture/operating-systems.md'
    - 'AWS': 'architecture/aws.md'
    - 'Azure': 'architecture/azure.md'
    - 'Bare-Metal': 'architecture/bare-metal.md'
    - 'Google Cloud': 'architecture/google-cloud.md'
  - 'Flatcar Linux':
    - 'AWS': 'cl/aws.md'
    - 'Azure': 'cl/azure.md'
    - 'Bare-Metal': 'cl/bare-metal.md'
    - 'Google Cloud': 'cl/google-cloud.md'
    - 'Packet': 'flatcar/packet.md'
  - 'Topics':
    - 'Maintenance': 'topics/maintenance.md'
    - 'Hardware': 'topics/hardware.md'
    - 'Security': 'topics/security.md'
    - 'Performance': 'topics/performance.md'
    - 'FAQ': 'topics/faq.md'
  - 'Advanced':
    - 'Overview': 'advanced/overview.md'
    - 'Customization': 'advanced/customization.md'
    - 'Worker Pools': 'advanced/worker-pools.md'
