{
 "title": "Ceph - OSD",
 "description": "CEPH OSD Status.",
 "tags": [
  "ceph",
  "osd"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "osd",
    "label": "OSD",
    "query": "label_values(ceph_osd_up, ceph_daemon)"
   }
  ]
 },
 "panels": [
  { "title": "OSD Status / Total OSDs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_osd_up{ceph_daemon=\"$osd\"}"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_osd_in{ceph_daemon=\"$osd\"}"
    }
   ]
  },
  {
   "title": "Total OSDs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(ceph_osd_up)" }
   ]
  },
  { "title": "OSD: $osd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "PGs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_numpg{ceph_daemon=~\"$osd\"}",
     "legendFormat": "Number of PGs - {{` {{ osd }} `}}"
    },
    {
     "expr": "avg(ceph_osd_numpg)",
     "legendFormat": "Average Number of PGs in the Cluster"
    }
   ]
  },
  {
   "title": "Utilization",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes_used{ceph_daemon=\"osd.0\"}/ceph_osd_stat_bytes{ceph_daemon=\"osd.0\"}"
    }
   ]
  },
  {
   "title": "Latency, Storage, Utilization Varience",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_apply_latency_ms{ceph_daemon=~\"$osd\"}",
     "legendFormat": "Apply Latency (s) - {{` {{ osd }} `}}"
    },
    {
     "expr": "ceph_osd_commit_latency_ms{ceph_daemon=~\"$osd\"}",
     "legendFormat": "Commit Latency (s) - {{` {{ osd }} `}}"
    }
   ]
  },
  {
   "title": "OSD Storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ceph_osd_stat_bytes{ceph_daemon=\"osd.0\"}-ceph_osd_stat_bytes_used{ceph_daemon=\"osd.0\"}",
     "legendFormat": "Available - {{` {{ osd }} `}}"
    },
    {
     "expr": "ceph_osd_stat_bytes_used{ceph_daemon=~\"$osd\"}",
     "legendFormat": "Used - {{` {{ osd }} `}}"
    }
   ]
  }
 ]
}