{
 "title": "Ceph - Pools",
 "description": "Ceph Pools dashboard.",
 "tags": [
  "ceph",
  "pools"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "pool",
    "label": "Pool",
    "query": "label_values(ceph_pool_metadata, pool_id)"
   }
  ]
 },
 "panels": [
  { "title": "Pool: $pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool Storage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ceph_pool_max_avail{pool_id=~\"^$pool$\"}",
     "legendFormat": "Avilable - {{ `{{ pool }}` }}"
    },
    {
     "expr": "ceph_pool_bytes_used{pool_id=~\"^$pool$\"}",
     "legendFormat": "Used - {{ `{{ pool }}` }}"
    },
    {
     "expr": "ceph_pool_bytes_used{pool_id=~\"^$pool$\"} + ceph_pool_max_avail{pool_id=~\"^$pool$\"}",
     "legendFormat": "Total - {{ `{{ pool }}` }}"
    },
    {
     "expr": "ceph_pool_raw_bytes_used{pool_id=~\"^$pool$\"}",
     "legendFormat": "Raw - {{ `{{ pool }}` }}"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "ceph_pool_bytes_used{pool_id=\"$pool\"} / (ceph_pool_bytes_used{pool_id=\"$pool\"} + ceph_pool_max_avail{pool_id=\"$pool\"})"
    }
   ]
  },
  { "title": "Pool Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Objects in Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceph_pool_objects{pool_id=~\"$pool\"}",
     "legendFormat": "Objects - {{ `{{ pool }}` }}"
    },
    {
     "expr": "ceph_pool_dirty{pool_id=~\"$pool\"}",
     "legendFormat": "Dirty Objects - {{ `{{ pool }}` }}"
    },
    {
     "expr": "ceph_pool_quota_objects{pool_id=~\"$pool\"}",
     "legendFormat": "Quota Objects - {{ `{{ pool }}` }}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "IOPS" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_pool_rd{pool_id=~\"$pool\"}[3m])",
     "legendFormat": "Read - {{ `{{ pool }}` }}"
    },
    {
     "expr": "irate(ceph_pool_wr{pool_id=~\"$pool\"}[3m])",
     "legendFormat": "Write - {{ `{{ pool }}` }}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(ceph_pool_rd_bytes{pool_id=\"$pool\"}[$interval])",
     "legendFormat": "Read Bytes - {{ `{{ pool }}` }}"
    },
    {
     "expr": "irate(ceph_pool_wr_bytes{pool_id=\"$pool\"}[$interval])",
     "legendFormat": "Written Bytes - {{ `{{ pool }}` }}"
    }
   ]
  }
 ]
}