{{- if (.Values.installNamespace) -}}
---
###
### Linkerd Namespace
###
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}
  annotations:
    linkerd.io/inject: disabled
  labels:
    linkerd.io/is-control-plane: "true"
    config.linkerd.io/admission-webhooks: disabled
    linkerd.io/control-plane-ns: {{.Values.namespace}}
{{ end -}}
