{
 "title": "Contour - HTTPProxy",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Namespace", "query": "label_values(namespace)" },
   { "name": "VHost", "query": "label_values(vhost)" }
  ]
 },
 "panels": [
  {
   "title": "Total HTTProxies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(contour_httpproxy{namespace=~\"$Namespace\"}) by (namespace)",
     "legendFormat": "Namespace: {{ namespace }}"
    }
   ]
  },
  {
   "title": "Orphaned HTTProxies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(contour_httpproxy_orphaned{namespace=~\"$Namespace\"}) by (namespace)",
     "legendFormat": "Namespace: {{ namespace }}"
    }
   ]
  },
  {
   "title": "Valid HTTProxies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(contour_httpproxy_valid{namespace=~\"$Namespace\",vhost=~\"$VHost\"}) by (namespace,vhost)",
     "legendFormat": "Namespace: {{ namespace }} ({{ vhost }})"
    }
   ]
  },
  {
   "title": "Invalid HTTProxies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(contour_httpproxy_invalid{namespace=~\"$Namespace\",vhost=~\"$VHost\"}) by (namespace,vhost)",
     "legendFormat": "Namespace: {{ namespace }} ({{ vhost }})"
    }
   ]
  },
  {
   "title": "Root HTTProxies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(contour_httpproxy_root{namespace=~\"$Namespace\"}) by (namespace)",
     "legendFormat": "Namespace: {{ namespace }}"
    }
   ]
  },
  {
   "title": "Contour LDS Updates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_listener_manager_lds_update_failure",
     "legendFormat": "{{kubernetes_pod_name}} (failure)"
    },
    {
     "expr": "envoy_listener_manager_lds_update_success",
     "legendFormat": "{{kubernetes_pod_name}} (success)"
    },
    {
     "expr": "envoy_listener_manager_lds_update_rejected",
     "legendFormat": "{{kubernetes_pod_name}} (rejected)"
    }
   ]
  },
  {
   "title": "Contour CDS Updates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_manager_cds_update_success",
     "legendFormat": "{{kubernetes_pod_name}} (Success)"
    },
    {
     "expr": "envoy_cluster_manager_cds_update_failure",
     "legendFormat": "{{kubernetes_pod_name}} (Failure)"
    },
    {
     "expr": "envoy_cluster_manager_cds_update_rejected",
     "legendFormat": "{{kubernetes_pod_name}} (Rejected)"
    }
   ]
  },
  {
   "title": "Contour RDS Updates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_http_rds_update_success",
     "legendFormat": "{{kubernetes_pod_name}} (Success)"
    },
    {
     "expr": "envoy_http_rds_update_failure",
     "legendFormat": "{{kubernetes_pod_name}} (Failure)"
    },
    {
     "expr": "envoy_http_rds_update_rejected",
     "legendFormat": "{{kubernetes_pod_name}} (Rejected)"
    }
   ]
  }
 ]
}