# Default values for openebs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rbac:
  # Specifies whether RBAC resources should be created
  create: true
  pspEnabled: false

serviceAccount:
  create: true
  name:

imagePullSecrets:
  #  - name: image-pull-secret

release:
  # "openebs.io/version" label for control plane components
  version: "2.7.0"

image:
  pullPolicy: IfNotPresent
  repository: ""

apiserver:
  enabled: true
  image: "openebs/m-apiserver"
  imageTag: "2.7.0"
  replicas: 1
  ports:
    externalPort: 5656
    internalPort: 5656
  sparse:
    enabled: "false"
  nodeSelector: {}
  tolerations: []
  affinity: {}
  healthCheck:
    initialDelaySeconds: 30
    periodSeconds: 60
  ## apiserver resource requests and limits
  ## Reference: http://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
    # limits:
    #   cpu: 1000m
    #   memory: 2Gi
    # requests:
    #   cpu: 500m
    #   memory: 1Gi


defaultStorageConfig:
  enabled: "true"

# Directory used by the OpenEBS to store debug information and so forth
# that are generated in the course of running OpenEBS containers.
varDirectoryPath:
  baseDir: "/var/openebs"

provisioner:
  enabled: true
  image: "openebs/openebs-k8s-provisioner"
  imageTag: "2.7.0"
  replicas: 1
  enableLeaderElection: true
  patchJivaNodeAffinity: enabled
  nodeSelector: {}
  tolerations: []
  affinity: {}
  healthCheck:
    initialDelaySeconds: 30
    periodSeconds: 60
  ## provisioner resource requests and limits
  ## Reference: http://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
    # limits:
    #   cpu: 1000m
    #   memory: 2Gi
    # requests:
    #   cpu: 500m
    #   memory: 1Gi

localprovisioner:
  enabled: true
  image: "openebs/provisioner-localpv"
  imageTag: "2.7.0"
  replicas: 1
  enableLeaderElection: true
  basePath: "/var/openebs/local"
  nodeSelector: {}
  tolerations: []
  affinity: {}
  healthCheck:
    initialDelaySeconds: 30
    periodSeconds: 60
  ## localprovisioner resource requests and limits
  ## Reference: http://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
    # limits:
    #   cpu: 1000m
    #   memory: 2Gi
    # requests:
    #   cpu: 500m
    #   memory: 1Gi

snapshotOperator:
  enabled: true
  controller:
    image: "openebs/snapshot-controller"
    imageTag: "2.7.0"
    ## snapshot controller resource requests and limits
    ## Reference: http://kubernetes.io/docs/user-guide/compute-resources/
    resources: {}
      # limits:
      #   cpu: 1000m
      #   memory: 2Gi
      # requests:
      #   cpu: 500m
      #   memory: 1Gi
  provisioner:
    image: "openebs/snapshot-provisioner"
    imageTag: "2.7.0"
    ## snapshot provisioner resource requests and limits
    ## Reference: http://kubernetes.io/docs/user-guide/compute-resources/
    resources: {}
      # limits:
      #   cpu: 1000m
      #   memory: 2Gi
      # requests:
      #   cpu: 500m
      #   memory: 1Gi
  replicas: 1
  enableLeaderElection: true
  upgradeStrategy: "Recreate"
  nodeSelector: {}
  tolerations: []
  affinity: {}
  healthCheck:
    initialDelaySeconds: 30
    periodSeconds: 60

ndm:
  enabled: true
  image: "openebs/node-disk-manager"
  imageTag: "1.3.0"
  sparse:
    path: "/var/openebs/sparse"
    size: "10737418240"
    count: "0"
  filters:
    enableOsDiskExcludeFilter: true
    enableVendorFilter: true
    excludeVendors: "CLOUDBYT,OpenEBS"
    enablePathFilter: true
    includePaths: ""
    excludePaths: "/dev/loop,/dev/fd0,/dev/sr0,/dev/ram,/dev/dm-,/dev/md,/dev/rbd,/dev/zd"
  probes:
    enableSeachest: false
  nodeSelector: {}
  tolerations: []
  healthCheck:
    initialDelaySeconds: 30
    periodSeconds: 60
  ## ndm resource requests and limits
  ## Reference: http://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
    # limits:
    #   cpu: 1000m
    #   memory: 2Gi
    # requests:
    #   cpu: 500m
    #   memory: 1Gi

ndmOperator:
  enabled: true
  image: "openebs/node-disk-operator"
  imageTag: "1.3.0"
  replicas: 1
  upgradeStrategy: Recreate
  nodeSelector: {}
  tolerations: []
  healthCheck:
    initialDelaySeconds: 30
    periodSeconds: 60
  readinessCheck:
    initialDelaySeconds: 4
    periodSeconds: 10
    failureThreshold: 1
  ## ndmOperator resource requests and limits
  ## Reference: http://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
    # limits:
    #   cpu: 1000m
    #   memory: 2Gi
    # requests:
    #   cpu: 500m
    #   memory: 1Gi

webhook:
  enabled: true
  image: "openebs/admission-server"
  imageTag: "2.7.0"
  failurePolicy: "Fail"
  replicas: 1
  healthCheck:
    initialDelaySeconds: 30
    periodSeconds: 60
  nodeSelector: {}
  tolerations: []
  affinity: {}
  hostNetwork: false
  ## admission-server resource requests and limits
  ## Reference: http://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
    # limits:
    #   cpu: 500m
    #   memory: 1Gi
    # requests:
    #   cpu: 250m
    #   memory: 500Mi

jiva:
  image: "openebs/jiva"
  imageTag: "2.7.0"
  replicas: 3
  defaultStoragePath: "/var/openebs"

cstor:
  pool:
    image: "openebs/cstor-pool"
    imageTag: "2.7.0"
  poolMgmt:
    image: "openebs/cstor-pool-mgmt"
    imageTag: "2.7.0"
  target:
    image: "openebs/cstor-istgt"
    imageTag: "2.7.0"
  volumeMgmt:
    image: "openebs/cstor-volume-mgmt"
    imageTag: "2.7.0"

helper:
  image: "openebs/linux-utils"
  imageTag: "2.7.0"

featureGates:
  enabled: true
  GPTBasedUUID:
    enabled: true
    featureGateFlag: "GPTBasedUUID"
  APIService:
    enabled: false
    featureGateFlag: "APIService"
    address: "0.0.0.0:9115"
  UseOSDisk:
    enabled: false
    featureGateFlag: "UseOSDisk"

crd:
  enableInstall: true

policies:
  monitoring:
    enabled: true
    image: "openebs/m-exporter"
    imageTag: "2.7.0"

analytics:
  enabled: true
  # Specify in hours the duration after which a ping event needs to be sent.
  pingInterval: "24h"


# To cleanup the validatingwebhook just before deletion of the charts
# via a pre-delete webhook job
hyperkubeImage:
  repository: "k8s.gcr.io/hyperkube"
  tag: "v1.12.1"
  pullPolicy: "IfNotPresent"
