{{- if eq (int .Values.coredns.controlPlaneReplicas) 1 }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
  labels:
    k8s-app: coredns
    kubernetes.io/name: "CoreDNS"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      tier: control-plane
      k8s-app: coredns
  template:
    metadata:
      labels:
        tier: control-plane
        k8s-app: coredns
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
{{- template "coredns-containers" . }}
{{- end }}
