// Code generated by go-bindata.
// sources:
// manifests/default-network-policies/deny-metadata-access.yaml
// DO NOT EDIT!

package networkpolicy

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _manifestsDefaultNetworkPoliciesDenyMetadataAccessYaml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x44\x8c\xcf\x6a\x03\x21\x10\xc6\xef\x3e\xc5\xbc\x80\xee\x1f\xb6\xa5\xf5\x58\xe8\xb5\x14\x5a\x72\x17\x1d\x96\xc1\x5d\x47\x54\xb2\x59\x42\xde\x3d\xb8\x92\x44\x0f\xdf\xcc\x37\x3f\x7e\x26\xd2\x09\x53\x26\x0e\x1a\x02\x96\x8d\x93\xa7\x30\x2b\xff\x91\x15\x71\x77\x1e\x84\xa7\xe0\x34\xfc\xb4\xd3\x2f\x2f\x64\x77\xb1\x62\x31\xce\x14\xa3\x05\x40\x30\x2b\x6a\x70\x18\x76\x89\x73\xc2\x9c\x65\x61\x69\xb6\x2c\x1f\x90\xc8\x11\x6d\x25\x23\xbb\x3f\x5c\xd0\x16\x4e\x1a\xae\xb7\xa3\xa9\xba\xff\x3d\x62\xae\x80\x84\xef\xc3\x20\x00\x9a\xaa\x95\x85\x6b\xd6\x89\xe2\xd7\xc2\xd6\xb7\xb5\x3e\x4b\x2e\x69\xe8\xd5\xf1\xbb\xfe\xd9\xe3\xc5\x62\x2c\x2f\x4e\xc2\xf0\xfe\xa9\xc6\xb7\x49\xd5\xec\xbb\x71\x12\xf7\x00\x00\x00\xff\xff\x17\x6b\x3c\x84\xf9\x00\x00\x00")

func manifestsDefaultNetworkPoliciesDenyMetadataAccessYamlBytes() ([]byte, error) {
	return bindataRead(
		_manifestsDefaultNetworkPoliciesDenyMetadataAccessYaml,
		"manifests/default-network-policies/deny-metadata-access.yaml",
	)
}

func manifestsDefaultNetworkPoliciesDenyMetadataAccessYaml() (*asset, error) {
	bytes, err := manifestsDefaultNetworkPoliciesDenyMetadataAccessYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "manifests/default-network-policies/deny-metadata-access.yaml", size: 249, mode: os.FileMode(436), modTime: time.Unix(1538643498, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"manifests/default-network-policies/deny-metadata-access.yaml": manifestsDefaultNetworkPoliciesDenyMetadataAccessYaml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"manifests": {nil, map[string]*bintree{
		"default-network-policies": {nil, map[string]*bintree{
			"deny-metadata-access.yaml": {manifestsDefaultNetworkPoliciesDenyMetadataAccessYaml, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
