#!/bin/bash

set -euo pipefail

# TODO: We want to avoid cloning the entire repo.
# Related: https://github.com/kinvolk/lokoctl/issues/34
git clone -q git@github.com:kinvolk/lokomotive-kubernetes.git
pushd lokomotive-kubernetes 1>/dev/null
git checkout -q 87096e749626a742a656fa39ba1c38231b00241e
popd 1>/dev/null
tar zcf lokomotive-kubernetes-aws.tar.gz lokomotive-kubernetes/aws/container-linux/kubernetes
tar zcf lokomotive-kubernetes-baremetal.tar.gz lokomotive-kubernetes/bare-metal/container-linux/kubernetes
tar zcf lokomotive-kubernetes-packet.tar.gz lokomotive-kubernetes/packet/flatcar-linux/kubernetes

go-bindata -pkg aws -o pkg/install/aws/bindata.go lokomotive-kubernetes-aws.tar.gz
go-bindata -pkg baremetal -o pkg/install/baremetal/bindata.go lokomotive-kubernetes-baremetal.tar.gz
go-bindata -pkg packet -o pkg/install/packet/bindata.go lokomotive-kubernetes-packet.tar.gz
rm -rf lokomotive-kubernetes-*.tar.gz lokomotive-kubernetes
