#!/bin/bash

set -euo pipefail

# TODO: We want to avoid cloning the entire repo.
# Related: https://github.com/kinvolk/lokoctl/issues/34
git clone -q git@github.com:kinvolk/lokomotive-kubernetes.git
pushd lokomotive-kubernetes 1>/dev/null
git checkout -q 24da8c4ef11a75afc651e18ba73afaa429b4c311
popd 1>/dev/null

# We should create an idempotent tarball with same timestamps for all files,
# to be able to prevent dirty bindata from being generated every time.
export TZ=UTC
readonly TAR_OPTS="--sort=name --owner=root:0 --group=root:0 --mtime=2019-01-01"

tar ${TAR_OPTS} -cf - lokomotive-kubernetes/aws/container-linux/kubernetes | gzip -n > lokomotive-kubernetes-aws.tar.gz
tar ${TAR_OPTS} -cf - lokomotive-kubernetes/bare-metal/container-linux/kubernetes | gzip -n > lokomotive-kubernetes-baremetal.tar.gz
tar ${TAR_OPTS} -cf - lokomotive-kubernetes/packet/flatcar-linux/kubernetes | gzip -n > lokomotive-kubernetes-packet.tar.gz

go-bindata -nometadata -pkg aws -o pkg/install/aws/bindata.go lokomotive-kubernetes-aws.tar.gz
go-bindata -nometadata -pkg baremetal -o pkg/install/baremetal/bindata.go lokomotive-kubernetes-baremetal.tar.gz
go-bindata -nometadata -pkg packet -o pkg/install/packet/bindata.go lokomotive-kubernetes-packet.tar.gz
rm -rf lokomotive-kubernetes-*.tar.gz lokomotive-kubernetes
