#!/bin/bash

set -euo pipefail

# TODO: We want to avoid cloning the entire repo. We want to avoid this.
# Related: https://github.com/kinvolk/lokoctl/issues/34
git clone -q git@github.com:kinvolk/lokomotive-kubernetes.git
pushd lokomotive-kubernetes 1>/dev/null
git reset HEAD -q 99a6d5478b8d3b2f747681960790dad5aa373138
popd 1>/dev/null
tar zcf lokomotive-kubernetes.tar.gz lokomotive-kubernetes/aws/container-linux/kubernetes

go-bindata -pkg aws -o pkg/install/aws/bindata.go lokomotive-kubernetes.tar.gz
rm -rf lokomotive-kubernetes.tar.gz lokomotive-kubernetes
