#!/bin/bash

set -euo pipefail

componentArchives=()

echo -e "Creating tarballs...\\n"

for f in ./manifests/*; do
  # Create tarball only if $f is a directory and not a symbolic link.
  if [[ -d "${f}" && ! -L "${f}" ]]; then
    filename="${f}".tar.gz
    componentArchives+=("${filename}")
    tar zcf "${filename}" "${f}"
    echo -e "${filename}"
  fi
done

echo -e "\\nEmbedding all the tarballs into pkg/components/bindata.go\\n"
go-bindata -pkg components -o pkg/components/bindata.go "${componentArchives[@]}"

echo "Removing tarballs from manifests/"
# Clean up of all the tarballs.
for f in "${componentArchives[@]}"; do
  rm "${f}"
  echo "${f}"
done
