# XXX: Lokomotive specific change.
{{- if or (eq .Values.cloudProvider "packet" (or (eq .Values.cloudProvider "azure") (and (eq .Values.cloudProvider "aws") (not (has "" (list .Values.awsAccessKeyID .Values.awsSecretAccessKey)))))) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cluster-autoscaler.fullname" . }}
data:
{{- if eq .Values.cloudProvider "azure" }}
  ClientID: "{{ .Values.azureClientID | b64enc }}"
  ClientSecret: "{{ .Values.azureClientSecret | b64enc }}"
  ResourceGroup: "{{ .Values.azureResourceGroup | b64enc }}"
  SubscriptionID: "{{ .Values.azureSubscriptionID | b64enc }}"
  TenantID: "{{ .Values.azureTenantID | b64enc }}"
  VMType: "{{ .Values.azureVMType | b64enc }}"
  ClusterName: "{{ .Values.azureClusterName | b64enc }}"
  NodeResourceGroup: "{{ .Values.azureNodeResourceGroup | b64enc }}"
{{- else if eq .Values.cloudProvider "aws" }}
  AwsAccessKeyId: "{{ .Values.awsAccessKeyID | b64enc }}"
  AwsSecretAccessKey: "{{ .Values.awsSecretAccessKey | b64enc }}"
# XXX: Lokomotive specific change.
{{- else if eq .Values.cloudProvider "packet" }}
type: Opaque
stringData:
  cloud-config: |-
    [Global]
    project-id={{ .Values.packetProjectID }}
    api-server-endpoint={{ .Values.apiServer }}
    facility={{ .Values.packetFacility }}
    plan={{ .Values.packetNodeType }}
    billing=hourly
    os=flatcar_{{ .Values.packetOSChannel }}
    cloudinit="{{ .Values.packetCloudInit }}"
    reservation=none
    hostname-pattern={{ printf "%s" "{{.ClusterName}}-{{.NodeGroup}}-{{.RandString8}}" }}
{{- end }}
{{- end }}
# XXX: Lokomotive specific change.
---
{{- if (eq .Values.cloudProvider "packet") }}
apiVersion: v1
data:
  authtoken: {{ .Values.packetAuthToken }}
kind: Secret
metadata:
  name: cluster-autoscaler-packet-token
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}
