# Set provider name and backup storage location bucket name
configuration:
  provider: aws
  backupStorageLocation:
    bucket: velero
    config:
      region: us-west-1
      profile: test
  volumeSnapshotLocation:
    provider: aws
    config:
      bucket: velero
      region: us-west-1

schedules:
  mybackup:
    labels:
      myenv: foo
    schedule: "0 0 * * *"
    template:
      ttl: "240h"
      includedNamespaces:
      - foo

# Set a service account so that the CRD clean up job has proper permissions to delete CRDs
serviceAccount:
  server:
    name: velero

# Whether or not to clean up CustomResourceDefintions when deleting a release.
# Cleaning up CRDs will delete the BackupStorageLocation and VolumeSnapshotLocation instances, which would have to be reconfigured.
# Backup data in object storage will _not_ be deleted, however Backup instances in the Kubernetes API will.
# Always clean up CRDs in CI.
cleanUpCRDs: true
