apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubelet
  namespace: kube-system
  labels:
    tier: node
    k8s-app: kubelet
spec:
  selector:
    matchLabels:
      tier: node
      k8s-app: kubelet
  template:
    metadata:
      labels:
        tier: node
        k8s-app: kubelet
    spec:
      initContainers:
      - name: ca-syncer
        image: {{ .Values.image }}
        command:
        - bash
        - -c
        - |
          sed -i "s/^    certificate-authority-data:.*$/    certificate-authority-data: {{ required "kubernetesCACert can't be empty" .Values.kubernetesCACert }}/g" /var/lib/kubelet/kubeconfig /etc/kubernetes/kubeconfig
        volumeMounts:
        - name: var-lib-kubelet
          mountPath: /var/lib/kubelet
          readOnly: false
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
          readOnly: false
      containers:
      - name: kubelet
        image: {{ .Values.image }}
        command:
        - /bin/sh
        - -c
        # File /etc/kubernetes/kubelet.env on each host has the `taints` and `labels` that bootstrap
        # kubelet uses. This mechanism here makes sure that the same labels and taints are used in
        # this kubelet as well.
        args:
        - |
          echo "/usr/local/bin/kubelet \
          --node-ip=$(HOST_IP)  \
          --anonymous-auth=false \
          --authentication-token-webhook \
          --authorization-mode=Webhook \
          --client-ca-file=/etc/kubernetes/ca.crt \
          --cluster_dns={{ .Values.clusterDNS }} \
          {{- if .Values.cloudProvider }}
          --cloud-provider={{ .Values.cloudProvider }} \
          {{- end }}
          --cluster_domain={{ .Values.clusterDomain }} \
          --cni-conf-dir=/etc/cni/net.d \
          --config=/etc/kubernetes/kubelet.config \
          {{- if .Values.enableTLSBootstrap }}
          --kubeconfig=/var/lib/kubelet/kubeconfig \
          --bootstrap-kubeconfig=/etc/kubernetes/kubeconfig \
          --rotate-certificates \
          {{- else }}
          --kubeconfig=/etc/kubernetes/kubeconfig \
          {{- end }}
          --lock-file=/var/run/lock/kubelet.lock \
          --network-plugin=cni \
          --pod-manifest-path=/etc/kubernetes/manifests \
          --read-only-port=0 \
          --volume-plugin-dir=/var/lib/kubelet/volumeplugins \
          --node-labels=$(grep NODE_LABELS /etc/kubernetes/kubelet.env | cut -d'"' -f2) \
          --register-with-taints=$(grep NODE_TAINTS /etc/kubernetes/kubelet.env | cut -d'"' -f2) \
          --address=$(HOST_IP)
          " | tee /tmp/start-kubelet.sh &&
          chmod +x /tmp/start-kubelet.sh &&
          /tmp/start-kubelet.sh
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        securityContext:
          privileged: true
        volumeMounts:
        # This has two directories `networks` and `cache`.
        # cache: This directory is used by CNI to store cache files.
        # networks: Certain network providers use this directory.
        - mountPath: /var/lib/cni
          name: coreos-var-lib-cni
          readOnly: false
        # This is needed so that the Calico CNI plugin can read the file named `nodename` in the
        # following path. This file is created by `calico-node` daemonset pod.
        - mountPath: /var/lib/calico
          name: coreos-var-lib-calico
          readOnly: true
        # This directory has CNI plugin binaries.
        - mountPath: /opt/cni/bin
          name: coreos-opt-cni-bin
          readOnly: true
        - name: dev
          mountPath: /dev
          readOnly: false
        # Here kubelet stores the lock file and unix sockets.
        - name: run
          mountPath: /run
          readOnly: false
        - name: sys
          mountPath: /sys
          readOnly: false
        # This is mounted so that node local storage works fine.
        - name: mnt
          mountPath: /mnt
          mountPropagation: Bidirectional
        # This directory has certs that kubelet needs to authenticate.
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
          readOnly: true
        # This is needed so that kubelet can access the logs (which are symlinked) of the
        # containers. The CAdvisor (which is baked into kubelet) needs access to monitor the
        # container and report via kubelet monitoring endpoint.
        - name: var-lib-docker
          mountPath: /var/lib/docker
          readOnly: false
        - name: var-lib-kubelet
          mountPath: /var/lib/kubelet
          mountPropagation: Bidirectional
          # Logs from the pods.
        - name: logs
          mountPath: /var/log/pods
          readOnly: false
          # This is mounted from host to make sure that the kubelet showcases OS as Flatcar and not
          # Debian from the kubelet image.
        - name: os-release
          mountPath: /etc/os-release
          readOnly: true
        - name: etc-machine-id
          mountPath: /etc/machine-id
          readOnly: true
        - name: etc-resolv
          mountPath: /etc/resolv.conf
          readOnly: true
        - name: modules
          mountPath: /lib/modules
          readOnly: true
        # Kubelet looks for the CNI config files here.
        - name: etc-cni-netd
          mountPath: /etc/cni/net.d
          readOnly: true
      hostNetwork: true
      hostPID: true
      # Tolerate all the taints. This ensures that the pod runs on all the nodes.
      # https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
      tolerations:
      - operator: "Exists"
      volumes:
      - name: coreos-var-lib-cni
        hostPath:
          path: /var/lib/cni
      - name: etc-cni-netd
        hostPath:
          path: /etc/cni/net.d
      - name: coreos-var-lib-calico
        hostPath:
          path: /var/lib/calico
      - name: coreos-opt-cni-bin
        hostPath:
          path: /opt/cni/bin
      - name: dev
        hostPath:
          path: /dev
      - name: run
        hostPath:
          path: /run
      - name: sys
        hostPath:
          path: /sys
      - name: mnt
        hostPath:
          path: /mnt
      - name: etc-kubernetes
        hostPath:
          path: /etc/kubernetes
      - name: var-lib-docker
        hostPath:
          path: /var/lib/docker
      - name: var-lib-kubelet
        hostPath:
          path: /var/lib/kubelet
      - name: logs
        hostPath:
          path: /var/log/pods
      - name: os-release
        hostPath:
          path: /usr/lib/os-release
          type: File
      - name: etc-machine-id
        hostPath:
          path: /etc/machine-id
          type: File
      - name: etc-resolv
        hostPath:
          path: /etc/resolv.conf
          type: File
      - name: modules
        hostPath:
          path: /lib/modules
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
