controllerManager:
  serviceAccountKey: ${serviceaccount_key}
  caCert: ${ca_cert}
  caKey: ${ca_key}
  image: ${kube_controller_manager_image}
  cloudProvider: ${cloud_provider}
  serviceCIDR: ${service_cidr}
  podCIDR: ${pod_cidr}
  controlPlaneReplicas: ${control_plane_replicas}
  trustedCertsDir: ${trusted_certs_dir}
kubeProxy:
  image: ${kube_proxy_image}
  podCIDR: ${pod_cidr}
  trustedCertsDir: ${trusted_certs_dir}
kubeScheduler:
  image: ${kube_scheduler_image}
  controlPlaneReplicas: ${control_plane_replicas}
kubeConfigInCluster:
  server: ${server}
coredns:
  clusterDomainSuffix: ${cluster_domain_suffix}
  controlPlaneReplicas: ${control_plane_replicas}
  image: ${coredns_image}
  clusterIP: ${cluster_dns_service_ip}
etcd:
  %{~ if length(etcd_endpoints) > 0 ~}
  endpoints:
  %{~ for f in etcd_endpoints ~}
  - ${f}
  %{~ endfor ~}
  %{~ else ~}
  endpoints: []
  %{~ endif ~}
kubelet:
  enableTLSBootstrap: ${enable_tls_bootstrap}
